# Generated by Django 4.1 on 2022-08-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.IntegerField(verbose_name='Crime ID')),
                ('crime_type', models.CharField(max_length=100, verbose_name='Original Crime Type Name')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('call_date', models.DateField(verbose_name='Call Date')),
                ('offense_date', models.DateField(verbose_name='Offense Date')),
                ('call_time', models.TimeField(verbose_name='Call Time')),
                ('call_datetime', models.DateTimeField(verbose_name='Call Date Time')),
                ('disposition', models.CharField(default='Not recorded', max_length=50, verbose_name='Disposition')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('agency_id', models.SmallIntegerField(verbose_name='Agency ID')),
                ('address_type', models.CharField(max_length=100, verbose_name='Address Type')),
                ('common_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Common Location')),
            ],
        ),
        migrations.AddIndex(
            model_name='appeals',
            index=models.Index(fields=['-report_date'], name='report_date_idx'),
        ),
    ]
