CREATE TABLE "appeals" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "crime_id" integer NOT NULL, 
    "crime_type" varchar(100) NOT NULL, 
    "report_date" date NOT NULL, 
    "call_date" date NOT NULL, 
    "offense_date" date NOT NULL, 
    "call_time" time NOT NULL, 
    "call_datetime" timestamp with time zone NOT NULL, 
    "disposition" varchar(50) NOT NULL, 
    "address" varchar(100) NOT NULL, 
    "city" varchar(100) NOT NULL, 
    "state" varchar(50) NOT NULL, 
    "agency_id" smallint NOT NULL, 
    "address_type" varchar(100) NOT NULL, 
    "common_location" varchar(100) NULL
    );

CREATE INDEX "report_date_idx" ON "appeals" ("report_date" DESC);